stages:
  - build
  - tests

.job-push: &job-push
  artifacts:
    paths:
    - logs
    - manaplus/logs
    when: always
    expire_in: 3 week
  dependencies: []

.job-always: &job-always
  artifacts:
    paths:
    - logs
    - manaplus/logs
    when: always
    expire_in: 3 week
  dependencies: []

mxe_gcc6_shared_32_testsbin:
  stage: build
  script:
  - ls /mxe
  - ./tools/ci/jobs/mxe_gcc6_tests.sh --without-gameclient --without-dyecmd
  artifacts:
    paths:
    - logs
    untracked: true
    when: always
    expire_in: 1 week
  dependencies: []
  image: registry.gitlab.com/manaplus/mxe:gcc6_shared_32
  variables:
    PACKAGES: bash
    CROSS: i686-w64-mingw32.shared
  tags:
    - docker

mxe_gcc6_shared_64_testsbin:
  stage: build
  script:
  - ls /mxe
  - ./tools/ci/jobs/mxe_gcc6_tests.sh --without-gameclient --without-dyecmd
  artifacts:
    paths:
    - logs
    untracked: true
    when: always
    expire_in: 1 week
  dependencies: []
  image: registry.gitlab.com/manaplus/mxe:gcc6_shared_64
  variables:
    PACKAGES: bash
    CROSS: x86_64-w64-mingw32.shared
  tags:
    - docker

.mxe_gcc6_shared_32_tests:
  stage: tests
  script:
  - tools\ci\jobs\windowstest.cmd files32
  - dir
  artifacts:
    paths:
    - logs
    when: always
    expire_in: 3 week
  dependencies:
    - mxe_gcc6_shared_32_testsbin
  when: manual
  tags:
    - windows

.mxe_gcc6_shared_64_tests:
  stage: tests
  script:
  - tools\ci\jobs\windowstest.cmd files64
  artifacts:
    paths:
    - logs
    when: always
    expire_in: 3 week
  dependencies:
    - mxe_gcc6_shared_64_testsbin
  when: manual
  tags:
    - windows
