.job-push: &job-push
  artifacts:
    paths:
    - logs
    - manaplus/logs
    when: always
    expire_in: 3 week
  dependencies: []

.job-always: &job-always
  artifacts:
    paths:
    - logs
    - manaplus/logs
    when: always
    expire_in: 3 week
  dependencies: []

gcc-3_sdl1:
  stage: build
  script:
  - ./tools/ci/jobs/gcc3.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: registry.gitlab.com/manaplus/images:gentoo_gcc3_sdl1
  <<: *job-push
  variables:
    PMUPDATE: "echo"
    PMINSTALL: "echo"
  tags:
    - docker

gcc-3_sdl2:
  stage: build
  script:
  - ./tools/ci/jobs/gcc3.sh --with-sdl2
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: registry.gitlab.com/manaplus/images:gentoo_gcc3_sdl2
  <<: *job-push
  variables:
    PMUPDATE: "echo"
    PMINSTALL: "echo"
  tags:
    - docker
