.job-push: &job-push
  artifacts:
    paths:
    - logs
    when: always
    expire_in: 3 week
  dependencies: []

.job-always: &job-always
  artifacts:
    paths:
    - logs
    when: always
    expire_in: 3 week
  dependencies: []

clang-7.0_tests:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/clang70_tests.sh --without-dyecmd --without-gameclient
  <<: *job-push
  image: debian:buster
  variables:
    PACKAGES: clang-7 libc++-dev libc++abi-dev libclang-7-dev 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              git valgrind
  tags:
    - docker

clang-7.0_tests_i386:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/clang70_tests.sh --without-dyecmd --without-gameclient
  <<: *job-push
  image: i386/debian:buster
  variables:
    PACKAGES: clang-7 libc++-dev libc++abi-dev libclang-7-dev 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              git valgrind
  tags:
    - docker

clang-7.0_tests_sdl2:
  stage: build
  script:
  - ./tools/ci/jobs/clang70_tests.sh --with-sdl2 --without-dyecmd --without-gameclient
  <<: *job-push
  image: debian:buster
  variables:
    PACKAGES: clang-7 libc++-dev libc++abi-dev libclang-7-dev 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
              git valgrind
  tags:
    - docker

clang-7.0_tests_sdl2_i386:
  stage: build
  script:
  - ./tools/ci/jobs/clang70_tests.sh --with-sdl2 --without-dyecmd --without-gameclient
  <<: *job-push
  image: i386/debian:buster
  variables:
    PACKAGES: clang-7 libc++-dev libc++abi-dev libclang-7-dev 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
              git valgrind
  tags:
    - docker

clang-7.0:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/clang70.sh
  - ./tools/ci/scripts/runtests.sh
  <<: *job-push
  image: debian:buster
  variables:
    PACKAGES: clang-7 libc++-dev libc++abi-dev libclang-7-dev 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              git gdb valgrind netcat-openbsd procps
  tags:
    - docker

clang-7.0_i386:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/clang70.sh
  - ./tools/ci/scripts/runtests.sh
  <<: *job-push
  image: i386/debian:buster
  variables:
    PACKAGES: clang-7 libc++-dev libc++abi-dev libclang-7-dev 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              git gdb valgrind netcat-openbsd procps
  tags:
    - docker

clang-7.0_sdl2:
  stage: build
  script:
  - ./tools/ci/jobs/clang70.sh --with-sdl2
  - ./tools/ci/scripts/runtests.sh
  <<: *job-push
  image: debian:buster
  variables:
    ABOUTYOFFSET: 380
    PACKAGES: clang-7 libc++-dev libc++abi-dev libclang-7-dev 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
              git gdb valgrind netcat-openbsd procps
  tags:
    - docker

clang-7.0_sdl2_i386:
  stage: build
  script:
  - ./tools/ci/jobs/clang70.sh --with-sdl2
  - ./tools/ci/scripts/runtests.sh
  <<: *job-push
  image: i386/debian:buster
  variables:
    ABOUTYOFFSET: 380
    PACKAGES: clang-7 libc++-dev libc++abi-dev libclang-7-dev 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
              git gdb valgrind netcat-openbsd procps
  tags:
    - docker
