parameters:
  name: ''
  xcode: ''
  vmImage: 'macOS-latest'

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: '${{ parameters.vmImage }}'
  steps:
  - script: |
      export xcodename="${{ parameters.xcode }}"
      export artifacts="$(Build.ArtifactStagingDirectory)"
      ./tools/ci/jobs/xcode.sh
    env:
      GITLABTOKEN: $(gitlabtoken)
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: ${{ parameters.name }}
