.job-push: &job-push
  artifacts:
    paths:
    - logs
    - manaplus/logs
    when: always
    expire_in: 3 week
  dependencies: []

.job-always: &job-always
  artifacts:
    paths:
    - logs
    - manaplus/logs
    when: always
    expire_in: 3 week
  dependencies: []

gcc-7_sanitize_doctest_tests:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_sanitize_tests.sh --enable-unittests=doctest --without-dyecmd --without-gameclient
  - ldd ./src/manaplustests | grep "libasan"
  image: debian:buster
  <<: *job-push
  variables:
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
    JOBS: 1
  tags:
    - docker

gcc-7_doctest_tests_i386:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_tests.sh --enable-unittests=doctest --without-dyecmd --without-gameclient
  image: i386/debian:buster
  <<: *job-push
  variables:
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
    JOBS: 1
  tags:
    - docker

gcc-7_tests_simd:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_tests_simd.sh --without-dyecmd --without-gameclient
  image: debian:buster
  <<: *job-push
  variables:
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
  tags:
    - docker

gcc-7_tests_O0:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_tests_simd.sh --without-dyecmd --without-gameclient
  image: debian:buster
  <<: *job-push
  variables:
    POST_CXXFLAGS: "-O0"
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
  tags:
    - docker

gcc-7_tests_O1:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_tests_simd.sh --without-dyecmd --without-gameclient
  image: debian:buster
  <<: *job-push
  variables:
    POST_CXXFLAGS: "-O1"
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
  tags:
    - docker

gcc-7_tests_lto:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_tests.sh --without-dyecmd --without-gameclient
  image: debian:buster
  <<: *job-push
  variables:
    POST_CXXFLAGS: "-ffast-math -O9 -flto -fwhole-program -funswitch-loops"
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
  tags:
    - docker

gcc-7_tests_lto_i386:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_tests.sh --without-dyecmd --without-gameclient
  <<: *job-push
  image: i386/debian:buster
  variables:
    POST_CXXFLAGS: "-ffast-math -O9 -flto -fwhole-program -funswitch-loops"
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
  tags:
    - docker

gcc-7_tests_i386:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_tests.sh --without-dyecmd --without-gameclient
  image: i386/debian:buster
  <<: *job-push
  variables:
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
  tags:
    - docker

gcc-7_tests_flags:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_tests.sh --without-dyecmd --without-gameclient --enable-glibcdebug
  - ./tools/ci/jobs/gcc7_tests.sh --without-dyecmd --without-gameclient --enable-stldebug
  image: debian:buster
  <<: *job-push
  variables:
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
  tags:
    - docker

gcc-7_tests:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_tests.sh --without-dyecmd --without-gameclient
  image: debian:buster
  <<: *job-push
  variables:
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
  tags:
    - docker

gcc-7_sdl2_tests_i386:
  stage: build
  script:
  - ./tools/ci/jobs/gcc7_tests.sh --with-sdl2 --without-dyecmd --without-gameclient
  image: i386/debian:buster
  <<: *job-push
  variables:
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev 
              git valgrind
  tags:
    - docker

.gcc-7_tests_valgrind:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_tests.sh --without-dyecmd --without-gameclient || true
  - echo test valgrind
  - valgrind -q --read-var-info=yes --track-origins=yes --malloc-fill=11 --free-fill=55 --show-reachable=yes --leak-check=full --leak-resolution=high --partial-loads-ok=yes --error-limit=no ./src/manaplustests 2>logs/valg.log
  - grep "invalid" logs/valg.log && exit 1 || true
  image: debian:buster
  <<: *job-push
  variables:
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
  tags:
    - docker

.gcc-7_tests_valgrind_i386:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_tests.sh --without-dyecmd --without-gameclient || true
  - echo test valgrind
  - valgrind -q --read-var-info=yes --track-origins=yes --malloc-fill=11 --free-fill=55 --show-reachable=yes --leak-check=full --leak-resolution=high --partial-loads-ok=yes --error-limit=no ./src/manaplustests 2>logs/valg.log
  - grep "invalid" logs/valg.log && exit 1 || true
  image: i386/debian:buster
  <<: *job-push
  variables:
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
  tags:
    - docker

gcc-7_separate_doctest:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_silent.sh --enable-unittestsbin=doctest --without-gameclient --without-dyecmd
  - ./tools/ci/scripts/separateunittests.sh
  image: debian:buster
  <<: *job-push
  variables:
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git python

gcc-7_separate_doctest_sanitize:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_silent.sh --enable-unittestsbin=doctest --without-gameclient --without-dyecmd
  - ./tools/ci/scripts/separateunittests.sh
  - ldd ./src/manaplustests | grep "libasan"
  image: debian:buster
  <<: *job-push
  variables:
    LSAN_OPTIONS: "suppressions=./tools/ci/scripts/lsansuppression_tests.txt"
    POST_CXXFLAGS: "-D_GLIBCXX_SANITIZE_VECTOR
                    -fsanitize=address -fsanitize=undefined
                    -fsanitize=shift -fsanitize=integer-divide-by-zero -fsanitize=unreachable
                    -fsanitize=vla-bound -fsanitize=null -fsanitize=return
                    -fsanitize=signed-integer-overflow -fsanitize=bounds -fsanitize=alignment
                    -fsanitize=object-size -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow
                    -fsanitize=nonnull-attribute -fsanitize=returns-nonnull-attribute -fsanitize=bool
                    -fsanitize=enum -fsanitize=vptr -fsanitize=bounds-strict"
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git python
  tags:
    - docker

gcc-7_separate_doctest_sanitize_sdl2:
  stage: build
  script:
  - ./tools/ci/jobs/gcc7_silent.sh --enable-unittestsbin=doctest --without-gameclient --without-dyecmd --with-sdl2
  - ./tools/ci/scripts/separateunittests.sh
  - ldd ./src/manaplustests | grep "libasan"
  image: debian:buster
  <<: *job-push
  variables:
    LSAN_OPTIONS: "suppressions=./tools/ci/scripts/lsansuppression_tests.txt"
    POST_CXXFLAGS: "-D_GLIBCXX_SANITIZE_VECTOR
                    -fsanitize=address -fsanitize=undefined
                    -fsanitize=shift -fsanitize=integer-divide-by-zero -fsanitize=unreachable
                    -fsanitize=vla-bound -fsanitize=null -fsanitize=return
                    -fsanitize=signed-integer-overflow -fsanitize=bounds -fsanitize=alignment
                    -fsanitize=object-size -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow
                    -fsanitize=nonnull-attribute -fsanitize=returns-nonnull-attribute -fsanitize=bool
                    -fsanitize=enum -fsanitize=vptr -fsanitize=bounds-strict"
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
              git python
  tags:
    - docker

gcc-7_separate_doctest_i386:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_silent.sh --enable-unittestsbin=doctest --without-gameclient --without-dyecmd
  - ./tools/ci/scripts/separateunittests.sh
  <<: *job-push
  image: i386/debian:buster
  variables:
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git python
  tags:
    - docker

gcc-7_separate_doctest_sdl2_i386:
  stage: build
  script:
  - ./tools/ci/jobs/gcc7_silent.sh --enable-unittestsbin=doctest --without-gameclient --without-dyecmd --with-sdl2
  - ./tools/ci/scripts/separateunittests.sh
  <<: *job-push
  image: i386/debian:buster
  variables:
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
              git python
  tags:
    - docker

gcc-7_unsigned_char_tests:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc7_tests.sh --without-dyecmd --without-gameclient
  image: debian:buster
  <<: *job-push
  variables:
    POST_CXXFLAGS: "-funsigned-char"
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind
  tags:
    - docker

gcc-7_sdl2_unsigned_char_tests:
  stage: build
  script:
  - ./tools/ci/jobs/gcc7_tests.sh --with-sdl2 --without-dyecmd --without-gameclient
  image: debian:buster
  <<: *job-push
  variables:
    POST_CXXFLAGS: "-funsigned-char"
    PACKAGES: gcc-7 g++-7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev 
              git valgrind
  tags:
    - docker
