.job-push: &job-push
  artifacts:
    paths:
    - logs
    when: always
    expire_in: 3 week
  dependencies: []

.job-always: &job-always
  artifacts:
    paths:
    - logs
    when: always
    expire_in: 3 week
  dependencies: []

gcc-8_tests_jmalloc:
  stage: build
  script:
  - ls ${MALLOC}
  - ./tools/ci/scripts/patchsdl1.sh
  - LD_PRELOAD=${MALLOC} ./tools/ci/jobs/gcc8_tests.sh --without-dyecmd --without-gameclient
  <<: *job-push
  variables:
    PACKAGES: gcc-8 g++-8 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind libjemalloc2
    MALLOC: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
  tags:
    - docker

gcc-8_tests_jmalloc_i386:
  stage: build
  script:
  - ls ${MALLOC}
  - ./tools/ci/scripts/patchsdl1.sh
  - LD_PRELOAD=${MALLOC} ./tools/ci/jobs/gcc8_tests.sh --without-dyecmd --without-gameclient
  <<: *job-push
  image: i386/debian:unstable
  variables:
    PACKAGES: gcc-8 g++-8 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind libjemalloc2
    MALLOC: /usr/lib/i386-linux-gnu/libjemalloc.so.2
  tags:
    - docker

gcc-8_tests_jmalloc_sdl2:
  stage: build
  script:
  - ls ${MALLOC}
  - LD_PRELOAD=${MALLOC} ./tools/ci/jobs/gcc8_tests.sh --with-sdl2 --without-dyecmd --without-gameclient
  <<: *job-push
  variables:
    PACKAGES: gcc-8 g++-8 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
              git valgrind libjemalloc2
    MALLOC: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
  tags:
    - docker

gcc-8_tests_jmalloc_sdl2_i386:
  stage: build
  script:
  - ls ${MALLOC}
  - LD_PRELOAD=${MALLOC} ./tools/ci/jobs/gcc8_tests.sh --with-sdl2 --without-dyecmd --without-gameclient
  <<: *job-push
  image: i386/debian:unstable
  variables:
    PACKAGES: gcc-8 g++-8 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
              git valgrind libjemalloc2
    MALLOC: /usr/lib/i386-linux-gnu/libjemalloc.so.2
  tags:
    - docker

gcc-8_tests_tcmalloc:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc8_tests.sh --enable-tcmalloc --without-dyecmd --without-gameclient
  <<: *job-push
  variables:
    PACKAGES: gcc-8 g++-8 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind libgoogle-perftools-dev
  tags:
    - docker

gcc-8_tests_tcmalloc_i386:
  stage: build
  script:
  - ./tools/ci/scripts/patchsdl1.sh
  - ./tools/ci/jobs/gcc8_tests.sh --enable-tcmalloc --without-dyecmd --without-gameclient
  <<: *job-push
  image: i386/debian:unstable
  variables:
    PACKAGES: gcc-8 g++-8 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev 
              git valgrind libgoogle-perftools-dev
  tags:
    - docker

gcc-8_tests_tcmalloc_sdl2:
  stage: build
  script:
  - ./tools/ci/jobs/gcc8_tests.sh --enable-tcmalloc --with-sdl2 --without-dyecmd --without-gameclient
  <<: *job-push
  variables:
    PACKAGES: gcc-8 g++-8 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
              git valgrind libgoogle-perftools-dev
  tags:
    - docker

gcc-8_tests_tcmalloc_sdl2_i386:
  stage: build
  script:
  - ./tools/ci/jobs/gcc8_tests.sh --enable-tcmalloc --with-sdl2 --without-dyecmd --without-gameclient
  <<: *job-push
  image: i386/debian:unstable
  variables:
    PACKAGES: gcc-8 g++-8 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
              git valgrind libgoogle-perftools-dev
  tags:
    - docker
